targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        enabled: true
        generate_for:
          - lib/config/injection/injection.dart
      json_serializable:
        enabled: true
        generate_for:
          - lib/features/*/data/models/*.dart
          - lib/core/models/*.dart